### PR TITLE
Create question_SymbatB04.md

### PR DESCRIPTION
**Pull request by Symbat051195**
Final exam questions! Please teacher add my questions!!!!

### CODE REVIEW

**Comment by Symbat051195** [comment]
Teacher final questions please add my questions!!!!

**Comment by Symbat051195** [comment]
Please add my questions!

**Comment by konsteacher** [comment]
Please, follow the format. Create each question by typing ``mktemp question_XXXX --suffix=.md`` locally on your computer. Then commit all of them at once (it will be easier for me to read). Push your commits to your forks master branch...

**Comment by konsteacher** [comment]
Please follow the format in README.md

**Comment by konsteacher** [comment]
Too long not responding.
Make a separate new pull request when you get ready.

**Pull request closed without merging**
